LangString addOrReinstall ${LANG_SIMPCHINESE} "添加/重新安装组件"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已经安装。请选择您要执行的操作，然后点击“下一步”继续。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！请先关闭它，然后重试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！$\n点击“确定”以强制关闭并继续。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "选择要执行的维护操作。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "选择您想要安装 ${PRODUCTNAME} 的方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "请勿卸载"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "请勿卸载（此安装程序禁止在未卸载旧版本的情况下直接降级）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法关闭 {{product_name}}！请在任务管理器中手动结束进程后重试。"
LangString installerLanguageTitle ${LANG_SIMPCHINESE} "安装程序语言"
LangString installerLanguagePrompt ${LANG_SIMPCHINESE} "请选择安装程序使用的语言："
LangString uninstallerLanguageTitle ${LANG_SIMPCHINESE} "卸载程序语言"
LangString uninstallerLanguagePrompt ${LANG_SIMPCHINESE} "请选择卸载程序使用的语言："
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "检测到系统中已安装更新版本的 ${PRODUCTNAME}。无法直接安装较旧版本。"
LangString olderVersionInstalled ${LANG_SIMPCHINESE} "检测到系统中已安装较旧版本的 ${PRODUCTNAME}。建议在安装前先卸载旧版本。"
LangString reinstall ${LANG_SIMPCHINESE} "重新安装"
LangString uninstall ${LANG_SIMPCHINESE} "卸载"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallPreviousVersion ${LANG_SIMPCHINESE} "卸载旧版本"
LangString webview2NotInstalled ${LANG_SIMPCHINESE} "未检测到 Microsoft Edge WebView2 Runtime。安装程序将尝试自动下载并安装。"
LangString webview2DownloadFailed ${LANG_SIMPCHINESE} "WebView2 下载失败，请手动安装 Microsoft Edge WebView2 后重试。"

